apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: ticket/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: ticket/client
      context: client
      sync:
        manual:
          - src: app/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
